name: safetyproject
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  geocoding: ^3.0.0
  geolocator: ^13.0.0
  url_launcher: ^6.3.0
  flutter_sms: ^3.0.1
  telephony: ^0.2.0
  location: ^8.0.0
  google_maps_flutter: ^2.9.0
  flutter_polyline_points: ^2.0.0
  audioplayers: ^6.0.0
  flutter_phone_direct_caller: ^2.1.1
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  permission_handler: ^11.0.0
  flutter_native_splash: ^2.4.0
  google_fonts: ^6.2.1
  shake: ^3.0.0
  shared_preferences: ^2.3.0
  flutter_foreground_task: ^8.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0
  sqflite_common_ffi: ^2.3.0
  path_provider_platform_interface: ^2.1.0
  plugin_platform_interface: ^2.1.0
  permission_handler_platform_interface: ^4.0.0
  fake_async: ^1.3.1

flutter_native_splash:
  color: "#06080E"
  color_dark: "#06080E"
  image: assets/splash.png
  android: true
  ios: true
  android_12:
    color: "#06080E"
    color_dark: "#06080E"
    image: assets/splash.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FF2E45"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
