// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfBEDDNcpZNakUiOFeAkVJmof8gxgpCFk',
    appId: '1:405608367816:web:5552f3e67ba106024a07fd',
    messagingSenderId: '405608367816',
    projectId: 'safety-project-71d83',
    authDomain: 'safety-project-71d83.firebaseapp.com',
    databaseURL: 'https://safety-project-71d83-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'safety-project-71d83.firebasestorage.app',
    measurementId: 'G-6H99VPYCM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_k1Wx9BoOoQxpxS6McgJaVW2K54o9iro',
    appId: '1:405608367816:android:6d5d63a0b20dd0da4a07fd',
    messagingSenderId: '405608367816',
    projectId: 'safety-project-71d83',
    databaseURL: 'https://safety-project-71d83-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'safety-project-71d83.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWiEvQAJE7fzDVB05etYaMHUfE4y3e8_g',
    appId: '1:405608367816:ios:1d417ef4d65432da4a07fd',
    messagingSenderId: '405608367816',
    projectId: 'safety-project-71d83',
    databaseURL: 'https://safety-project-71d83-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'safety-project-71d83.firebasestorage.app',
    iosClientId: '405608367816-9v58i29mvtngt38c0mk9t7rf29lsgqtl.apps.googleusercontent.com',
    iosBundleId: 'com.elatreby.safety',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWiEvQAJE7fzDVB05etYaMHUfE4y3e8_g',
    appId: '1:405608367816:ios:6592926df1bd302b4a07fd',
    messagingSenderId: '405608367816',
    projectId: 'safety-project-71d83',
    databaseURL: 'https://safety-project-71d83-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'safety-project-71d83.firebasestorage.app',
    iosClientId: '405608367816-efe0ascc6rf6g5t1k40klvv0o75esosa.apps.googleusercontent.com',
    iosBundleId: 'com.elatreby.safety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfBEDDNcpZNakUiOFeAkVJmof8gxgpCFk',
    appId: '1:405608367816:web:6470f2f1ecad7f8b4a07fd',
    messagingSenderId: '405608367816',
    projectId: 'safety-project-71d83',
    authDomain: 'safety-project-71d83.firebaseapp.com',
    databaseURL: 'https://safety-project-71d83-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'safety-project-71d83.firebasestorage.app',
    measurementId: 'G-5YNF1H671K',
  );
}
